apiVersion: v1
kind: Pod
metadata:
  labels:
    run: readiness-exec
  name: readiness-exec
spec:
  containers:
  - image: k8s.gcr.io/busybox
    name: readiness
    args:
    - /bin/sh
    - -c
    - sleep 60; touch /tmp/healthy; while true; do sleep 10000; done
    readinessProbe:
      exec:
        command:
        - cat
        - /tmp/healthy
      initialDelaySeconds: 0
      periodSeconds: 5
      failureThreshold: 3
